name: Python application
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install xvfb
      run: |
          sudo apt-get install xvfb
    - name: Run tests under xvfb
      run: |
        xvfb-run --auto-servernum python setup.py test
    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1
    - uses: actions/upload-artifact@master
      with:
          name: failed-image
          path: test/failed-image
